// <auto-generated />
namespace Project_ISP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class firstChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201912120500341_firstChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
